hw4
petcheetos/backend-java-course pull request #4
Opened 2024-03-07 21:44 UTC by petcheetos

2024-03-15 18:56 UTC, nexen505 requested changes

2024-03-15 18:56 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            liquibase.update(new Contexts(), new LabelExpression());
Проблема: у меня локально миграции падают

```
java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: org.postgresql.util.PSQLException: Подсоединение по адресу localhost:32784 отклонено. Проверьте что хост и порт указаны правильно и что postmaster принимает TCP/IP-подсоединения.
	at edu.java.scrapper.IntegrationTest.runMigrations(IntegrationTest.java:56)
	at edu.java.scrapper.IntegrationTest.<clinit>(IntegrationTest.java:32)
	... 8 more
Caused by: org.postgresql.util.PSQLException: Подсоединение по адресу localhost:32784 отклонено. Проверьте что хост и порт указаны правильно и что postmaster принимает TCP/IP-подсоединения.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
	at org.postgresql.Driver.makeConnection(Driver.java:443)
	at org.postgresql.Driver.connect(Driver.java:297)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at edu.java.scrapper.IntegrationTest.runMigrations(IntegrationTest.java:36)
	... 9 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
	... 16 more


Process finished with exit code 255
```

Предложение: указать в настройках контейнера ожидания порта (см. `Wait#forListeningPort()`)

2024-03-15 18:56 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            var database = DatabaseFactory.getInstance().
Проблема: ресурс не закрывается.

Предложение: воспользоваться try-with-resources.

2024-03-15 18:56 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            var liquibase = new Liquibase(
Проблема: ресурс не закрывается.

Предложение: воспользоваться try-with-resources.

2024-03-15 20:00 UTC, petcheetos commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            var database = DatabaseFactory.getInstance().
когда я использую try-with-resources, у меня падает тест 
![image](https://github.com/petcheetos/backend-java-course/assets/114106870/7fe30c4c-3ecf-4314-a404-0fb6d738f72d)
без каких-либо изменений, вроде бы, все запускается 
![image](https://github.com/petcheetos/backend-java-course/assets/114106870/47dade29-ccad-4a0d-8f97-0da1ec8277a6)

2024-03-15 20:20 UTC, petcheetos commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            liquibase.update(new Contexts(), new LabelExpression());
добавлено

2024-03-28 14:18 UTC, nexen505 approved these changes

2024-03-28 14:22 UTC, merged