hw5
petcheetos/backend-java-course pull request #5
Opened 2024-03-17 20:14 UTC by petcheetos

2024-03-17 21:04 UTC, petcheetos commented
тут небольшая проблема: локально все тесты проходят, а здесь нет :( можете, пожалуйста, подсказать, в чем причина и как это исправить

2024-04-01 11:49 UTC, nexen505 requested changes

2024-04-01 11:49 UTC, nexen505 commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcChatRepository.java
> +    @Transactional
Проблема: транзакцию здесь необязательно открывать на запись.

Предложение: тут и в других местах использовать параметр `readonly` в случае запросов на чтение.

2024-04-01 11:49 UTC, nexen505 commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcChatRepository.java
> +    @Transactional
Косметика: если метод содержит один запрос, то в целом некритично указывать здесь транзакционность.
Это имеет смысл в случае применения нестандартных транзакций (изоляция, чтение и т.п.) или необходимости объединения нескольких запросов в одну транзакцию.

2024-04-01 11:49 UTC, nexen505 commented on scrapper/src/main/java/edu/java/repository/mappers/ChatLinkExtractor.java
> +            if (!res.contains(chatLinkDTO)) {
Проблема: этот поиск имеет линейную сложность, что приводит к квадратичной сложности парсинга.

Предложение: если есть необходимости группировать, то лучше сначала собрать мапу, а потом из entries мапы собрать объекты.

2024-04-01 11:49 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scheduler/LinkUpdaterScheduler.java
> +            if (linkProcessor.isGithubUrl(linkDTO.url())) {
Проблема: весь этот код сложно читать.

Предложение: порефакторить для удобства восприятия (например, можно вынести приватные методы для обработки разных типов ссылок).

2024-04-01 11:49 UTC, nexen505 commented on scrapper/src/main/java/edu/java/services/jdbc/JdbcChatService.java
> +        if (chatRepository.exist(chatId)) {
Проблема: запрос лишний, так как метод добавления и так выбросит ошибку при конфликте идентификаторов.

Предложение: убрать его в пользу ошибки следующего.

2024-04-01 11:49 UTC, nexen505 commented on scrapper/src/main/java/edu/java/services/jdbc/JdbcChatService.java
> +        if (!chatRepository.exist(chatId)) {
Проблема: лишний запрос, хотя можно обработать результат запроса `delete`.

Предложение: оптимизировать работу с БД, убрав ненужные запросы.

2024-04-01 11:49 UTC, nexen505 commented on scrapper/src/main/java/edu/java/services/jdbc/JdbcLinkService.java
> +        checkChatDoesNotExist(chatId);
Мысль: думаю, тут необязательно это проверять, так как соседний запрос просто может вернуть пустой список.

2024-04-01 11:49 UTC, nexen505 commented on scrapper/src/main/java/edu/java/services/jdbc/JdbcLinkService.java
> +        checkChatDoesNotExist(chatId);
Проблема: этот запрос лишний, так как добавление при отсутствии связанной строки в таблице и так выбросит ошибку.

Предложение: оптимизировать работу с БД, убрав лишний запрос.

2024-04-01 11:49 UTC, nexen505 commented on scrapper/src/main/java/edu/java/services/jdbc/JdbcLinkService.java
> +        checkChatDoesNotExist(chatId);
Проблема: запрос лишний, так как можно обработать результат `delete`.

Предложение: оптимизировать работу с БД.

2024-04-02 18:49 UTC, petcheetos commented on scrapper/src/main/java/edu/java/scheduler/LinkUpdaterScheduler.java
> +            if (linkProcessor.isGithubUrl(linkDTO.url())) {
исправлено

2024-04-08 07:08 UTC, nexen505 approved these changes

2024-04-09 07:05 UTC, merged